version: '3.8'

services:
  app:
    image: uherdockerhub/my-dockerhub:latest    # ← ดึงจาก Docker Hub
    container_name: my_test_project
    ports:
      - "3011:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s