version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_test_project
    ports:
      - "3011:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
