name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, test-server-project]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop old container
        run: docker stop my_test_project || true

      - name: Remove old container
        run: docker rm my_test_project || true

      - name: Build Docker image
        run: docker build -t my_test_project:latest .

      - name: Run Docker container
        run: |
          docker run -d \
            --name my_test_project \
            -p 3011:3000 \
            --restart unless-stopped \
            my_test_project:latest
